name: Run tests from application

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:

  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

